---
sudo: false
language: ruby
#cache: bundler
rvm:
  - 2.2.4
matrix:
  include:
  - env: OPENSTUDIO_VERSION=2.8.1 && OPENSTUDIO_SHA=6914d4f590 && RUBYLIB=/usr/local/openstudio-2.8.1/Ruby:/usr/Ruby
before_install: 
  - gem install bundler -v '1.17'
  - gem install bundler -v '~> 1.17'
install: 
  - bundle install
before_script:
  - curl -sLO https://raw.githubusercontent.com/NREL/OpenStudio-server/develop/docker/deployment/scripts/install_openstudio.sh
  - chmod +x install_openstudio.sh
  - sudo ./install_openstudio.sh $OPENSTUDIO_VERSION $OPENSTUDIO_SHA
script:
  - bundle exec rake 
  - bundle exec rake openstudio:list_measures
  - bundle exec rake openstudio:update_measures
  - bundle exec rake openstudio:test_with_openstudio
