# Test with OpenStudio container
name: test_with_openstudio

# trigger action on all branches, pull requests and tags
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: nrel/openstudio:3.5.1

    steps:
      - uses: actions/checkout@v2
      - name: show enviroment
        shell: bash
        run: |
          ruby -v
          openstudio openstudio_version
          openstudio gem_list
      - name: set git config options
         shell: bash
         run: |
           git config --global --add safe.directory
      - name: install dependencies
        shell: bash
        run: |
          gem install bundler -v '2.1.4'
          bundle -v
          bundle install
      - name: run tests
        shell: bash
        run: |
          bundle exec rake
          bundle exec rake openstudio:list_measures
          bundle exec rake openstudio:update_measures
          bundle exec rake openstudio:test_with_openstudio
      - name: collect stats, display and check for failures
        shell: bash
        run: |
          test_dir=$(find -type d -name "test_results")
          echo $test_dir
          mv $test_dir . 
      - uses: actions/upload-artifact@v3
        name: save artifacts
        with:
          name: test_results
          path: test_results

          
        
        

